---
version: "3"
services:
  ttc:
    image: bluepostit/ttc
    container_name: ttc
    environment:
      - PORT=${TTC_PORT}
      - USER_EMAIL=${TTC_USER_EMAIL}
      - USER_PASSWORD=${TTC_USER_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      # Eg. data/modules.yaml
      - DATA_TREE_MANIFEST_PATH=${DATA_TREE_MANIFEST_PATH}
      # Eg. data
      - DATA_TREE_DATA_PATH=${DATA_TREE_DATA_PATH}
      - DISABLE_AUTH=false
      - VERSION_FILE_NAME=${VERSION_INFO_FILE_PATH-version-info.yaml}
      - CACHE_DB_PATH=${CACHE_DB_PATH-cache/cache.db}
    volumes:
      - ${DATA_TREE_DATA_HOST_PATH}:/usr/src/app/data
      # Allows the mapping of the cache directory to a volume
      - ${CACHE_DIR_HOST_PATH-./cache}:/usr/src/app/cache
    networks:
      - swag
    restart: unless-stopped

networks:
  swag:
    external: true
    name: swag
