---
version: "3"
services:
  ttc:
    image: bluepostit/ttc
    container_name: ttc
    environment:
      - PORT=${TTC_PORT}
      - USER_EMAIL=${TTC_USER_EMAIL}
      - USER_PASSWORD=${TTC_USER_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      # Eg. data/modules.yaml
      - MODULE_MANIFEST_PATH=${MODULE_MANIFEST_PATH}
      # Eg. data
      - MODULE_DATA_PATH=${MODULE_DATA_PATH}
      - DISABLE_AUTH=false
    volumes:
      - ${MODULE_DATA_HOST_PATH}:/usr/src/app/data
    networks:
      - swag
    restart: unless-stopped

networks:
  swag:
    external: true
    name: swag
